[package]
name = "web"
version = "0.1.0"
authors = ["xiongxin <1781189926@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-session = "0.3"
actix-rt = "1.0"
listenfd = "0.3"