# 自定义配置项
spring:
  datasource:
    dbcp2:
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
      initial-size: 5
      min-idle: 2
      max-total: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
  messages:
    basename: validation
logging:
  level:
    root: info
server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
#  servlet:
#    session:
#      timeout: 1