[package]
name = "redis_protocol"
version = "0.1.0"
authors = ["熊鑫 <1781189926@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.21"
anyhow = "1.0.33"